//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Donations_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationSite
    {
        public int DonationSiteID { get; set; }
        public string SiteName { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.TimeSpan EventStartDate { get; set; }
        public System.TimeSpan EventEndDate { get; set; }
        public string RegistrationEmail { get; set; }
        public string RegistrationPhone { get; set; }
        public string VenueName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
    }
}
