//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Donations_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationID { get; set; }
        public string DonationType { get; set; }
        public string CrossBloodType { get; set; }
        public string CrossRhFactor { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public double NumberOfUnits { get; set; }
        public string DonationSite { get; set; }
        public System.Guid DonationIdentifier { get; set; }
    }
}
