//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Donations_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public bool ActiveDonor { get; set; }
        public string DonorFirstName { get; set; }
        public string DonorLastName { get; set; }
        public string BloodType { get; set; }
        public string RhFactor { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<double> Wight { get; set; }
        public string DonorEmail { get; set; }
        public string DonorPhoneNumber { get; set; }
        public System.DateTime LastScreeningDate { get; set; }
        public System.Guid DonorIdentifier { get; set; }
    }
}
